"""Export real XAUUSD OHLC bars from MetaTrader 5 into xauusd_history.js
for trading_journey_v2.html. Run while MT5 terminal is open/logged in.

Usage: python export_history.py
"""
import json
import sys
from datetime import datetime, timezone

import MetaTrader5 as mt5

OUT = r"C:\Users\User\Desktop\xtrades\xauusd_history.js"
SYMBOL = "XAUUSD"

# key must match the HTML timeframe buttons
TFS = [
    ("1min", mt5.TIMEFRAME_M1, 5000),
    ("2min", mt5.TIMEFRAME_M2, 5000),
    ("5min", mt5.TIMEFRAME_M5, 6000),
    ("15min", mt5.TIMEFRAME_M15, 6000),
    ("30min", mt5.TIMEFRAME_M30, 6000),
    ("1hour", mt5.TIMEFRAME_H1, 10000),
    ("4hour", mt5.TIMEFRAME_H4, 6000),
    ("daily", mt5.TIMEFRAME_D1, 4000),
]


def main():
    if not mt5.initialize():
        print("MT5 init FAILED:", mt5.last_error())
        return 1

    if not mt5.symbol_select(SYMBOL, True):
        print("symbol_select FAILED:", mt5.last_error())
        mt5.shutdown()
        return 1

    info = mt5.symbol_info(SYMBOL)
    if info is None:
        print("symbol_info FAILED")
        mt5.shutdown()
        return 1

    timeframes = {}
    total = 0
    for key, tf, count in TFS:
        rates = mt5.copy_rates_from_pos(SYMBOL, tf, 0, count)
        if rates is None or len(rates) == 0:
            print("skip %-6s : no data (%s)" % (key, mt5.last_error()))
            continue
        bars = [
            [
                int(r["time"]),
                round(float(r["open"]), 2),
                round(float(r["high"]), 2),
                round(float(r["low"]), 2),
                round(float(r["close"]), 2),
            ]
            for r in rates
        ]
        timeframes[key] = bars
        total += len(bars)
        first = datetime.fromtimestamp(bars[0][0], tz=timezone.utc)
        last = datetime.fromtimestamp(bars[-1][0], tz=timezone.utc)
        print(
            "%-6s : %6d bars  %s -> %s  last close %.2f"
            % (key, len(bars), first.date(), last.date(), bars[-1][4])
        )

    if not timeframes:
        print("no data at all, aborting")
        mt5.shutdown()
        return 1

    # bar timestamps are broker SERVER time (UTC+3 here); detect the offset so
    # the chart can label axes in Kuala Lumpur time (UTC+8)
    server_offset = 0
    h1 = mt5.copy_rates_from_pos(SYMBOL, mt5.TIMEFRAME_H1, 0, 1)
    now = datetime.now(timezone.utc).timestamp()
    if h1 is not None and len(h1) > 0:
        last_bar = int(h1[-1]["time"])
        age = now - last_bar  # bar is SERVER-stamped; forming bar => roughly -offset
        raw = last_bar - (now // 3600 * 3600)
        if -15 * 3600 <= age <= 14 * 3600:
            # forming/last bar during session => offset = bar_time - floor(now, 1h)
            server_offset = int(round(raw / 1800.0)) * 1800
        else:
            # market closed: reuse offset from previous export if present
            try:
                with open(OUT, "r", encoding="utf-8") as f:
                    import re
                    m = re.search(r'"server_offset"\s*:\s*(-?\d+)', f.read())
                    if m:
                        server_offset = int(m.group(1))
                        print("market closed (bar age %.1fh) - kept previous server_offset" % (age / 3600))
            except OSError:
                pass
    if abs(server_offset) > 14 * 3600:
        server_offset = 0
    print("server_offset: %+d s (server UTC%+d, KL = server %+d h)" % (
        server_offset, server_offset // 3600, (28800 - server_offset) // 3600))

    payload = {
        "symbol": SYMBOL,
        "server": (mt5.account_info().server if mt5.account_info() else ""),
        "digits": int(info.digits),
        "server_offset": server_offset,
        "updated": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "timeframes": timeframes,
    }
    js = (
        "// auto-generated by export_history.py - real XAUUSD bars from MT5\n"
        "window.XAUUSD_HISTORY = "
        + json.dumps(payload, separators=(",", ":"))
        + ";\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(js)

    mt5.shutdown()
    print("wrote %s (%.2f MB, %d bars)" % (OUT, len(js) / 1048576, total))
    return 0


if __name__ == "__main__":
    sys.exit(main())
